### ISSUE TITLE
NPE after autocompletion

### ISSUE THREAD

**Issue by Krasnyanskiy** [jline/jline2#178]
Maybe I missed something but how can I combine the completers in a single group?

```java
public class JLineExample {
    public static void main(String[] args) throws IOException {
        String line;
        ConsoleReader console = new ConsoleReader();
        console.setPrompt("> ");

        // Quit
        Completer quit = new StringsCompleter("quit");

        // Group #1
        Completer start = new StringsCompleter("start");
        Completer stop = new StringsCompleter("stop");

        // Group #2
        Completer propetry = new StringsCompleter("property");
        Completer hide = new StringsCompleter("hide");

        // Joint groups
        Completer executionGroup = new ArgumentCompleter(start, stop);
        Completer propertyGroup = new ArgumentCompleter(propetry, hide);
        Completer jointGroups = new ArgumentCompleter(executionGroup, propertyGroup);

        // Aggregator
        Completer aggregated = new AggregateCompleter(quit, jointGroups);

        console.addCompleter(aggregated);
        while ((line = console.readLine("> ")) != null) {
            if ("quit".equals(line.trim())) exit(1);
        }
    }
}
```
My code throws an exception when I run it.
```
 Exception in thread "main" java.lang.NullPointerException
        at jline.console.completer.ArgumentCompleter$AbstractArgumentDelimiter.delimit(ArgumentCompleter.java:283)
        at jline.console.completer.ArgumentCompleter.complete(ArgumentCompleter.java:116)
        at jline.console.completer.ArgumentCompleter.complete(ArgumentCompleter.java:152)
        at jline.console.completer.AggregateCompleter$Completion.complete(AggregateCompleter.java:121)
        at jline.console.completer.AggregateCompleter.complete(AggregateCompleter.java:80)
        at jline.console.ConsoleReader.complete(ConsoleReader.java:3261)
        at jline.console.ConsoleReader.readLine(ConsoleReader.java:2621)
        at jline.console.ConsoleReader.readLine(ConsoleReader.java:2269)
        at com.test.jline.JLineExample.main(JLineExample.java:52)

```

**Comment by gnodet** [comment]
In which condition is the NPE thrown exactly ?

**Comment by Krasnyanskiy** [comment]
When I press Tab key first time.

**Comment by gnodet** [comment]
Completers have not really been tested this way.
What works is AggregateCompleter(argument completers...)
with each ArgumentCompleter having StringsCompleter as children.

The ArgumentCompleter handles a give command, with each argument being a StringCompleter.

I think you need to rewrite your example according to those rules...

**Comment by gnodet** [comment]
See https://github.com/jline/jline2/commit/3ea93269deb20cbbb9d31bb049023100a2f95128 for an example.
I'm closing this issue, please reopen if you need.

**Comment by turbanoff** [comment]
Let's throw something more meaningful than NPE
