### ISSUE TITLE
ConsoleReader.printColumns with PaginationEnabled throws java.lang.StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by hyee** [jline/jline2#216]
If enable pagination and the strings contain ANSI escape chars, then may trigger this error.
Related code is:

    541 int wcwidth(CharSequence str, int start, int end, int pos) {
    542     int cur = pos;
    543     for (int i = start; i < end;) {
    544         int ucs;
    545         char c1 = str.charAt(i++);
My temp solution is to change "i < end" as "i < Math.min(end,str.length())"

Below is the error stack for reference:

    --More--java.lang.StringIndexOutOfBoundsException: String index out of range: 0
            at java.lang.AbstractStringBuilder.charAt(AbstractStringBuilder.java:203)
            at java.lang.StringBuilder.charAt(StringBuilder.java:72)
            at jline.console.ConsoleReader.wcwidth(ConsoleReader.java:545)
            at jline.console.ConsoleReader.back(ConsoleReader.java:1020)
            at jline.console.ConsoleReader.printColumns(ConsoleReader.java:3760)

**Comment by hyee** [comment]
Seems that the "back" function in printColumns doesn't work, the expectation should be the "--More--" chars to be cleared before filling the same line when scrolling to next page, however it doesn't.

Below is an example, you can see that the "more" chars still exists:

        OWNER  OBJECT_NAME                    SUBOBJECT_NAME OBJECT_ID DATA_OBJECT_ID OBJECT_TYPE 
        ------ ------------------------------ -------------- --------- -------------- ----------- 
        SYS    UNDO$                                                15             15 TABLE       
        SYS    C_COBJ#                                              29             29 CLUSTER     
        SYS    I_OBJ#                                                3              3 INDEX       
        SYS    PROXY_ROLE_DATA$                                     25             25 TABLE       
        SYS    I_IND1                                               41             41 INDEX       
        SYS    I_CDEF2                                              54             54 INDEX       
        SYS    I_OBJ5                                               40             40 INDEX       
        SYS    I_PROXY_ROLE_DATA$_1                                 26             26 INDEX       
        SYS    FILE$                                                17             17 TABLE       
        SYS    UET$                                                 13              8 TABLE       
        SYS    I_FILE#_BLOCK#                                        9              9 INDEX       
        SYS    I_FILE1                                              43             43 INDEX       
        SYS    I_CON1                                               51             51 INDEX       
        SYS    I_OBJ3                                               38             38 INDEX       
        SYS    I_TS#                                                 7              7 INDEX       
        SYS    I_CDEF4                                              56             56 INDEX       
        SYS    IND$                                                 19              2 TABLE       
        SYS    SEG$                                                 14              8 TABLE       
    --More--    SYS    C_TS#                                                 6              6 CLUS
        SYS    I_FILE2                                              44             44 INDEX       
        SYS    COL$                                                 21              2 TABLE       
        SYS    I_TS1                                                45             45 INDEX       
        SYS    I_UNDO2                                              35             35 INDEX       
        SYS    CLU$                                                  5              2 TABLE       
        ....

**Comment by hyee** [comment]
Hello, 
as test, no need to change line#545, instead, replace ConsoleReader line #3672 from original
    
    back(resources.getString("DISPLAY_MORE").length());
as 

    tputs("carriage_return");

can solve the issue
