### ISSUE TITLE
Issue when building on Windows 7

### ISSUE THREAD

**Issue by Redmega** [jline/jline2#236]
## Specs
- Windows 7 64 Bit
- Apache Maven 3.3.9
- Java version "1.8.0_77"
## Issue

During Maven build the test fails at the 4th test, gives me the following log stating the test failed at `System$$PowerMock0.getenv("OSV_CPUS")`.

Complete message:

```
Tests run: 4, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.545 sec <<< FAILURE! - in jline.TerminalFactoryTest
testConfigureDumbTerminalEmacs(jline.TerminalFactoryTest)  Time elapsed: 0.296 sec  <<< FAILURE!
java.lang.AssertionError: Expectation failure on verify:
    System$$PowerMock0.getenv("OSV_CPUS"): expected: 1, actual: 0
        at org.easymock.internal.MocksControl.verify(MocksControl.java:241)
        at org.powermock.api.easymock.internal.invocationcontrol.EasyMockMethodInvocationControl.verify(EasyMockMethodInvocationControl.java:132)
        at org.powermock.api.easymock.PowerMock.verifyClass(PowerMock.java:2272)

        at org.powermock.api.easymock.PowerMock.verify(PowerMock.java:1646)
        at org.powermock.api.easymock.PowerMock.verifyAll(PowerMock.java:1586)
        at jline.TerminalFactoryTest.testConfigureDumbTerminalEmacs(TerminalFactoryTest.java:85)
```

Running cmd in administrator mode gives me some further errors at the same point of the build:

```
Tests run: 4, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 0.651 sec <<< FAILURE! - in jline.TerminalFactoryTest
testConfigureDumbTerminalEmacs(jline.TerminalFactoryTest)  Time elapsed: 0.386 sec  <<< FAILURE!
java.lang.AssertionError:
  Expectation failure on verify:
    System$$PowerMock0.getenv("TERM"): expected: 1, actual: 0
    System$$PowerMock0.getenv("EMACS"): expected: 1, actual: 0
    System$$PowerMock0.getenv("INSIDE_EMACS"): expected: 1, actual: 0
    System$$PowerMock0.getenv("OSV_CPUS"): expected: 1, actual: 0
        at org.easymock.internal.MocksControl.verify(MocksControl.java:241)
        at org.powermock.api.easymock.internal.invocationcontrol.EasyMockMethodInvocationControl.verify(EasyMockMethodInvocationControl.java:132)
        at org.powermock.api.easymock.PowerMock.verifyClass(PowerMock.java:2272)

        at org.powermock.api.easymock.PowerMock.verify(PowerMock.java:1646)
        at org.powermock.api.easymock.PowerMock.verifyAll(PowerMock.java:1586)
        at jline.TerminalFactoryTest.testConfigureDumbTerminalEmacs(TerminalFactoryTest.java:85)
```

I wasn't able to find any info on this issue on github or the web.
If you need more info please let me know.

**Comment by Redmega** [comment]
When building a project with Maven in which JLine has been included as a dependency, everything functions as expected. It is only when doing a mvn install on the JLine source that this issue occurs.

**Comment by sigmasoldi3r** [comment]
### Got the same error
I have the exact same error #242, but im seeing that @gnodet is not paying attention to this issue (25 days ago is alot!)
I hope that the @jline team comes with a solution. Sad to see that hasn't a solution yet.

**Comment by rkrell** [comment]
> I have the exact same error #242, but im seeing that @gnodet is not paying attention to this issue (25 days ago is alot!)

Man, 25 days is nothing for a free project maintained by volunteers. Send a pull request if you know it better or if you have more time!

**Comment by sigmasoldi3r** [comment]
Sorry man, out there there are tons of projects that are left out unfinished, i thought that this was one... don't be that rude...

**Comment by rkrell** [comment]
> Sorry man, out there there are tons of projects that are left out unfinished, i thought that this was one... don't be that rude...
> btw you have lost a potential contributor.

I'm neither the maintainer nor a contributor to this project. I'm also just a consumer of this like you.
But I'm a maintainer of another one. And I don't have understanding for pressure of this kind from outside, assuming your personal problem is solved in a time which would fit you!
Nevertheless, don't blame it to this project, please.

**Comment by Redmega** [comment]
@sigmasoldi3r What he said didn't seem rude to me.. Anyway, this isn't really on topic for the issue.
