### ISSUE TITLE
Cannot compile/install JLine

### ISSUE THREAD

**Issue by sigmasoldi3r** [jline/jline2#242]
When I try to *install* I get some kind of failure during tests, and build fails.
I run: `mvn install`
### Is there a way to install even if the test fails?
* * *
__The Output:__
```
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building JLine 2.15-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-maven) @ jline ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ jline ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] skip non existing resourceDirectory D:\documents\JLibraries\JLine2Library\src\main\filtered-resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ jline ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 53 source files to D:\documents\JLibraries\JLine2Library\target\classes
[INFO] 
[INFO] --- animal-sniffer-maven-plugin:1.14:check (default) @ jline ---
[INFO] Checking unresolved references to org.codehaus.mojo.signature:java15:1.0
[INFO] 
[INFO] >>> maven-bundle-plugin:2.5.4:manifest (default) > process-classes @ jline >>>
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-maven) @ jline ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ jline ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] skip non existing resourceDirectory D:\documents\JLibraries\JLine2Library\src\main\filtered-resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ jline ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 53 source files to D:\documents\JLibraries\JLine2Library\target\classes
[INFO] 
[INFO] --- animal-sniffer-maven-plugin:1.14:check (default) @ jline ---
[INFO] Checking unresolved references to org.codehaus.mojo.signature:java15:1.0
[INFO] 
[INFO] <<< maven-bundle-plugin:2.5.4:manifest (default) < process-classes @ jline <<<
[INFO] 
[INFO] --- maven-bundle-plugin:2.5.4:manifest (default) @ jline ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ jline ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 6 resources
[INFO] skip non existing resourceDirectory D:\documents\JLibraries\JLine2Library\src\test\filtered-resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ jline ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.18.1:test (default-test) @ jline ---
[INFO] Surefire report directory: D:\documents\JLibraries\JLine2Library\target\surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running jline.console.completer.ArgumentCompleterTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.081 sec - in jline.console.completer.ArgumentCompleterTest
Running jline.console.completer.NullCompleterTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 sec - in jline.console.completer.NullCompleterTest
Running jline.console.completer.StringsCompleterTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 sec - in jline.console.completer.StringsCompleterTest
Running jline.console.completer.WhitespaceDelimiterTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in jline.console.completer.WhitespaceDelimiterTest
Running jline.console.ConsoleReaderTest
Tests run: 27, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.337 sec - in jline.console.ConsoleReaderTest
Running jline.console.EditLineTest
Tests run: 11, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.224 sec - in jline.console.EditLineTest
Running jline.console.history.FileHistoryTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec - in jline.console.history.FileHistoryTest
Running jline.console.history.HistoryTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.589 sec - in jline.console.history.HistoryTest
Running jline.console.history.MemoryHistoryTest
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec - in jline.console.history.MemoryHistoryTest
Running jline.console.HistorySearchTest
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.032 sec - in jline.console.HistorySearchTest
Running jline.console.KillRingTest
Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.047 sec - in jline.console.KillRingTest
Running jline.console.ViMoveModeTest
Tests run: 34, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.452 sec - in jline.console.ViMoveModeTest
Running jline.internal.ConfigurationTest
Tests run: 11, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.005 sec - in jline.internal.ConfigurationTest
Running jline.internal.CursesTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec - in jline.internal.CursesTest
Running jline.internal.InfoCmpTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in jline.internal.InfoCmpTest
Running jline.internal.LogTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec - in jline.internal.LogTest
Running jline.internal.TerminalLineSettingsTest
Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec - in jline.internal.TerminalLineSettingsTest
Running jline.readline.KeyMapTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec - in jline.readline.KeyMapTest
Running jline.TerminalFactoryTest
Tests run: 4, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.648 sec <<< FAILURE! - in jline.TerminalFactoryTest
testConfigureDumbTerminalEmacs(jline.TerminalFactoryTest)  Time elapsed: 0.248 sec  <<< FAILURE!
java.lang.AssertionError: 
  Expectation failure on verify:
    System$$PowerMock0.getenv("OSV_CPUS"): expected: 1, actual: 0
	at org.easymock.internal.MocksControl.verify(MocksControl.java:241)
	at org.powermock.api.easymock.internal.invocationcontrol.EasyMockMethodInvocationControl.verify(EasyMockMethodInvocationControl.java:132)
	at org.powermock.api.easymock.PowerMock.verifyClass(PowerMock.java:2272)
	at org.powermock.api.easymock.PowerMock.verify(PowerMock.java:1646)
	at org.powermock.api.easymock.PowerMock.verifyAll(PowerMock.java:1586)
	at jline.TerminalFactoryTest.testConfigureDumbTerminalEmacs(TerminalFactoryTest.java:85)


Results :

Failed tests: 
  TerminalFactoryTest.testConfigureDumbTerminalEmacs:85 
  Expectation failure on verify:
    System$$PowerMock0.getenv("OSV_CPUS"): expected: 1, actual: 0

Tests run: 141, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10.781 s
[INFO] Finished at: 2016-04-24T21:30:52+02:00
[INFO] Final Memory: 19M/292M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project jline: There are test failures.
[ERROR] 
[ERROR] Please refer to D:\documents\JLibraries\JLine2Library\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by sigmasoldi3r** [comment]
## NetBeans
#### Tried out in netbeans, test results in:
![failtestjline](https://cloud.githubusercontent.com/assets/13834659/14769990/397d99ca-0a66-11e6-8237-09a8673877b9.PNG)

**Comment by rkrell** [comment]
> Is there a way to install even if the test fails?

What about `mvn -DskipTests=true install` ?
See the Maven documentation. How to build in Maven is not subject to this project.

**Comment by sigmasoldi3r** [comment]
Never used maven, sorry.
