### ISSUE TITLE
NumberFormatException on ubuntu bionic

### ISSUE THREAD

**Issue by je-ik** [jline/jline2#292]
Output of `infocmp` slightly changed in Ubuntu Bionic, from e.g.
```
colors#8, cols#80, it#8, lines#24, pairs#64,
```
to e.g.
```
colors#0x100, cols#80, it#8, lines#24, pairs#0x7fff,
```
which causes
```
java.lang.NumberFormatException: For input string: "0x100"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.valueOf(Integer.java:766)
	at jline.internal.InfoCmp.parseInfoCmp(InfoCmp.java:59)
	at jline.UnixTerminal.parseInfoCmp(UnixTerminal.java:242)
	at jline.UnixTerminal.<init>(UnixTerminal.java:65)
	at jline.UnixTerminal.<init>(UnixTerminal.java:50)
```

**Comment by gnodet** [comment]
Duplicates #281 which has been fixed a year ago.

**Comment by je-ik** [comment]
Yes, I have already figured in out. Upgrade to newest version fixes this. My bad. :-)
