### ISSUE TITLE
Ability to silence fallback message

### ISSUE THREAD

**Issue by md-5** [jline/jline2#93]
````[ERROR] Terminal initialization failed; falling back to unsupported
java.lang.NoClassDefFoundError: Could not initialize class org.fusesource.jansi.internal.Kernel32
at org.fusesource.jansi.internal.WindowsSupport.getConsoleMode(WindowsSupport.java:50)
at jline.WindowsTerminal.getConsoleMode(WindowsTerminal.java:177)
at jline.WindowsTerminal.init(WindowsTerminal.java:80)
at jline.TerminalFactory.create(TerminalFactory.java:101)
at jline.TerminalFactory.get(TerminalFactory.java:159)
at jline.console.ConsoleReader.(ConsoleReader.java:227)
at jline.console.ConsoleReader.(ConsoleReader.java:219)
at jline.console.ConsoleReader.(ConsoleReader.java:207)
at net.md_5.bungee.BungeeCord.(BungeeCord.java:157)
at net.md_5.bungee.BungeeCord.main(BungeeCord.java:189)````
Older JLine versions didn't display it, and I really don't want to either - users think something is wrong.

**Comment by omajid** [comment]
> You can change the log stream used by jline2 by calling jline.internal.Log.setOutput(PrintStream). 

Sorry for jumping in an unrelated issue, but I was trying to disable logging myself for a different bug. This call to `Log.setOutput` doesn't work when using OSGi because the `jline.internal` package is not exported. Is there any other way to silence the warnings?

For more information, my use case is to disable the stack trace shown (not the error message itself, just the stack trace) when user enters a bad expansion, like `what!?!` at the jline input.
